### ISSUE TITLE
how to update/write?

### ISSUE THREAD

**Issue by ozexpert** [rrousselGit/provider#104]
Provider seems to be very clean when using MultiProvider and reading the object using Provider.of. 

However, how do we update the object if needed?

**Comment by rrousselGit** [comment]
Do you have an update example in mind?

This may be a use-case for #59

**Comment by ozexpert** [comment]
I have this Settings model where I store a theme. Whenever user wants to change this theme, normally using with Bloc Provider, i used to dispatch an action to update the object. But wasn't sure how i can do this with the Provider. Below example, won't let me change the object when `changeTheme` is called since the object i believe is immutable. 
```
import 'package:testapp/models/index.dart';
import 'package:testapp/services/index.dart';


class SettingsModel {
  Themes theme;

  SettingsModel({
    this.theme
  });

  static Future<SettingsModel> initial() async {
    final PrefService _pref = PrefService();

    return SettingsModel(
      theme: await _pref.getTheme()
    );
  }

  changeTheme(Themes theme) {
    this.theme = theme;
  }
}
```

**Comment by Nolence** [comment]
I have this same question. Right now, I'm actually storing all of my settings properties inside the `ChangeNotifier`  object so I don't have a `SettingsModel` like @ozexpert but I do have another object with `ChangeNotifier` whose properties include a contest model.

```dart
class RosterState with ChangeNotifier {
  Contest _contest;
}
```

I'm wondering about best practice. Should I make a helper method inside `RosterState` to handle mutating the contest:

```dart
updateContest(newPropertyValue) {
  _contest.property = newPropertyValue;
  notifyListeners();
}
```
Or do I alter the passed down contest inside the widget and just call `setState` (assuming its properties are not `final`)?

Or, and this is because I'm coming from `flutter_redux`, do I use the previously shown helper method to alter the contest in an functional way so I don't actually alter the properties in place?

```dart
// Inside Widget
Contest newContest = Contest.copyWith( property: newProperty );
rosterState.updateContest(newContest);
```

```dart
updateContest(Contest newContest) {
  _contest = newContest;
  notifyListeners();
}
```
Sorry if this is another question, it just seems very related.

**Comment by rrousselGit** [comment]
>  Below example, won't let me change the object when changeTheme is called since the object i believe is immutable.

`ChangeNotifier` is not immutable. In theory that should work (although your `changeTheme` method does not call `notifyListeners`).

> I'm wondering about best practice. Should I make a helper method inside RosterState to handle mutating the contest:

If you can make your changes using the immutable approach, do so! Try to avoid mutable variables as much as possible – although `ChangeNotifier` isn't necessarily the best solution for that.

**Comment by Nolence** [comment]
Thanks for answering @rrousselGit. Following your advice I moved everything over to `built_collection` and `built_value` and now just update the private variables in my state with new immutables. I'm not sure what you mean by `ChangeNotifier` not being the best solution though. Could you elaborate?

**Comment by rrousselGit** [comment]
Just because it exists doesn't mean that you should handle everything with `ChangeNotifierProvider`.

`Provider` + StatefulWidget + immutable data is pretty good too.

**Comment by Nolence** [comment]
Sounds good, thanks @rrousselGit!

**Comment by ozexpert** [comment]
I think we can close this. https://www.youtube.com/watch?v=vFxk_KJCqgk fantastic tutorial for this matter.
