### ISSUE TITLE
Should there be a provider factory constructor

### ISSUE THREAD

**Issue by scopendo** [rrousselGit/provider#124]
It's not a big deal, just curious why we are required to use ChangeNotifierProvider, StreamProvider, etc. instead of just passing the value to be injected to a factory method that returns a corresponding provider for the type of the value?

**Comment by rrousselGit** [comment]
Because that's not extensible, is magical, and doesn't always do what is desired.

Peoples can make their own providers with custom logic.

**Comment by scopendo** [comment]
It's not really magical, it's just OO.  Was more curious, as part of understanding provider, when it wouldn't do what was desired.  Fully appreciate that it's easy to do this oneself.  Thanks for answering.

**Comment by rrousselGit** [comment]
> when it wouldn't do what was desired

There's no requirement whatsoever to force peoples to pass a `ChangeNotifier` through `ChangeNotifierProvider`.

Some may want to just use `Provider`, and listen to the value on children with something like `AnimatedBuilder`. 

So in that sense, if we pass a subclass of `ValueNotifier` to such constructor, what is the behavior?
Because that class is compatible with both `Provider`, `ChangeNotifierProvider` , and `ValueListenableProvider` (without considering custom providers).

**Comment by scopendo** [comment]
I see.  Thank you for taking the time to clarify.
