### ISSUE TITLE
Passing parameters to Bloc constructor

### ISSUE THREAD

**Issue by mmcc007** [rrousselGit/provider#2]
Interesting pattern. Do you have a suggestion for how to use a Bloc that requires a parameter?
I have been using another inherited widget that I use to retrieve the parameter and inject it into Bloc. Is there a convenient way to use this pattern to manage such a case?

Also, the inherited widget apparently does not have a dispose. Does this not result in a possible memory leak if used in stateless widgets (which also does not have a dispose) and in other cases? What is the best way to dispose of Bloc resources?

Here is a project that uses a stateful widget as a Bloc provider that disposes Bloc resources:
https://github.com/boeledi/Streams-Block-Reactive-Programming-in-Flutter/blob/master/lib/blocs/bloc_provider.dart

Here is the article that discusses it:
https://www.didierboelens.com/2018/08/reactive-programming---streams---bloc/

What is the recommended method to manage memory, or am I missing something?

**Comment by rrousselGit** [comment]
I've discussed a bit with the author of this articles. He'll edit his article soon to likely include an inherited widget (and modify the part against inherited). As to obtain an InheritedWidget it is O(1) vs O(N) for simple stateful widgets.

I'll suggest him to use this library, which basically does the same stuff.


Good point on for the dispose. We can add an `onDispose` callback to the `StatefulProvider` which passes the current value.
So that we should be able to do :

```dart
StatefulBuilder<Bloc>(
  valueBuilder: (value) => value ?? Bloc(),
  onDispose: (value) => value?.dispose(),
  child: Whatever,
);
```

**Comment by rrousselGit** [comment]
https://github.com/rrousselGit/provider/commit/e1f2e10e0db3f23325a0340ecf54aa3aff3f4aca

I added the `onDispose` callback. 

Is it now?

**Comment by mmcc007** [comment]
Yes, that should allow me to inject parameters to my Bloc constructor and then dispose of my Bloc resources when the stateful provider is removed from the widget tree (thru the magic of the framework).  Looks good to me 👍
