### ISSUE TITLE
Should selector add a method shouldUpdate that we can control ourselves, and if we don't implement it we'll still implement `selected! = value`, so we can control the List refresh,

### ISSUE THREAD

**Issue by 2534290808** [rrousselGit/provider#221]
Should selector add a method shouldUpdate that we can control ourselves, and if we don't implement it we'll still implement `selected! = value`, so we can control the List refresh, as follows:
```dart
@override
  Widget build(BuildContext context) {
    final selected = widget.selector(context);

    if (oldWidget != widget || shouldUpdate!=null ? shouldUpdate(selected,value) : selected != value ) {
      value = selected;
      oldWidget = widget;
      cache = widget.builder(
        context,
        selected,
        widget.child,
      );
    }
    return cache;
  }
```
```dart
Selector < A, List<B> > (
     selector (_, A) = > a. list,
     builder: (_) = > SizedBox (),
     shouldUpdate: (newList, oldList) = > newList! = oldList || newList. length! = oldList. Length
)
```

_Originally posted by @2534290808 in https://github.com/rrousselGit/provider/issues/205#issuecomment-532949555_

**Comment by fantasy525** [comment]
@2534290808 you can try this package,[should_rebuild](https://pub.flutter-io.cn/packages/should_rebuild)

```
ShouldRebuild<Todo>(
    shouldRebuild: (oldWidget, newWidget) => oldWidget.counter != newWidget.counter,
    child: Todo(counter: counter,)
),
```

**Comment by GIfatahTH** [comment]
It is a little challenging to work with reference variables in `shouldUpdate` here and `updateShouldNotify` in `StreamProvider`. This is because reference variables have no old (past) and new (present) state, they only reference the actual state; so `newList != oldList` is always false. Even with objects, `oldCounter.count != newCounter.count ` is always false even if `count` is primitive and if we override the ==operator because both the old and new models refer to the same instance as Provider exposes the same instance the child widgets. To have a different instance, the new model should be instantiated as a new instance (this what happen with `didUpdateWidget(oldWidget)` or the old one should be cloned from the provided instance before mutating the state but cloning instance is not supported by Dart.

This is a representative example with StreamProvider which fails to update the view as a new value is emited. 
```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

class CounterModel {
  int counter;
  CounterModel(this.counter);

  @override
  bool operator ==(other) {
    print("other.counter ${other.counter}");
    print("counter $counter");
    return other is CounterModel && other.counter == counter;
  }

  @override
  int get hashCode => counter.hashCode;
}

class Model {
  StreamController _controller = StreamController<CounterModel>();

  Stream<CounterModel> get stream => _controller.stream;

  CounterModel counter = CounterModel(0);
  increment() {
    counter.counter++;
    _controller.sink.add(counter);
  }

  dispose() {
    _controller.close();
  }
}

final model = Model();

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamProvider<CounterModel>(
      builder: (context) => model.stream,
      child: Scaffold(appBar: AppBar(), body: MyHome()),
      updateShouldNotify: (before, after) {
        print(before?.counter);
        print(after?.counter);
        return before?.counter != after?.counter;
      },
    );
  }
}

class MyHome extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final value = Provider.of<CounterModel>(context)?.counter;
    print(value);
    return Center(
        child: Column(
      children: <Widget>[
        Text("$value"),
        RaisedButton(
          child: Text("add"),
          onPressed: model.increment,
        )
      ],
    ));
  }
}

```
I realized that even if I remove the `updateShouldNotify` the view will not rebuild because the last line the `updateShouldNotify` (see below)  will end to false with reference variables.

```dart
  @override
  bool updateShouldNotify(InheritedProvider<T> oldWidget) {
    if (_updateShouldNotify != null) {
      return _updateShouldNotify(oldWidget._value, _value);
    }
    return oldWidget._value != _value; //Alwasy false for reference variable
  }
```

**Comment by rrousselGit** [comment]
@GIfatahTH Right. Use immutable data as much as you can.

For example, it's a good idea to make a "clone" of lists, with `[...myList]`, when pushing them in a stream.

**Comment by GIfatahTH** [comment]
I think it is not always feasible. Think if I have two nested StreamProvide of Strings (user, and password), for this and following your advice, I sould do it like this:

**Comment by rrousselGit** [comment]
Why wouldn't it? Country/City are immutable too.

**Comment by GIfatahTH** [comment]
If I create a new instance of Country/City and push to the stream it will work (as I mentioned above, for updateShouldNotify to work we have either to create a new instance of clone the old one before mutating the state). But in case I have a somewhat big data model and I change just one variable, I have to instantiate it from scratch with the supposedly long constructor. It would be very nice to push the modified instance rather than creating a new instance which will be a little boilerplaty.

Thanks;

**Comment by firatcetiner** [comment]
Seems like this is implemented as shouldRebuild for Selector instances. Although it has absolutely zero effective documentation on how to properly use it.

**Comment by Markelm16** [comment]
I use `previous.length != next.length` with shouldRebuild to check if the list has changed but it always throws false.
