### ISSUE TITLE
Error after add notifyListeners ()

### ISSUE THREAD

**Issue by Karatla** [rrousselGit/provider#310]
Hi 
firstly thanks for all provider support .
I got a new problem by using provider
When I add notifyListeners ().flutter reply a error and I do not know why.
If I do not add notifyListeners () how I can listen this change.
![Image](https://i.imgur.com/2ySKdAl.jpg)![Image](https://i.imgur.com/5nTESmp.jpg)![Image](https://i.imgur.com/M9T1hbF.jpg)

And my flutter doctor all fine 
Flutter version is 1.12.13
![Image](https://i.imgur.com/0CDB9P6.jpg)

**Comment by egorbelibov** [comment]
@Karatla You're getting this exception because you're, most likely, calling **`notifyListeners()`** while the widget tree is building. As a result, some widgets may build before the mutation, while other widgets will build after the mutation. This could cause inconsistencies in your UI and is therefore not allowed. 

For more info check the FAQ section: https://github.com/rrousselGit/provider#i-use-changenotifier-and-i-have-an-exception-when-i-update-it-what-happens

**Comment by rrousselGit** [comment]
@egorbelibov  made a good explanation, so I'll close this
