### ISSUE TITLE
How to share a ChangeNotifier between two pages?

### ISSUE THREAD

**Issue by luohaohaha** [rrousselGit/provider#366]
I want both pages can listen to the data change of ChangeNotifier,  I know that initialization is possible in the runApp entry, but I don't want to put the initialization in the main entry. How do I pass ChangeNotifier when Navigator.push? How does the second page receive ChangeNotifier? I tried to receive in the second page's construction, but the first page will be rebuilt, so the first page cannot be received again. Please tell me what to do? Thank you, my english is not very good, sorry.

**Comment by rrousselGit** [comment]
```dart
final myNotifier = Provider.of<MyNotifier>(context);

Navigator.push(
  context,
  MaterialPageRoute(builder: (context) {
    return ChangeNotifierProvider.value(
      value: myNotifier,
      child: MyView(),
    );
  }),
);
```

**Comment by edisonpagtakhan** [comment]
Hi @rrousselGit! One way to also do this is to just pass the provider as a parameter to `MyView`. With this, the code would look like
```
Navigator.push(
  context,
  MaterialPageRoute(builder: (context) {
   return MyView(myNotifier);
  }),
)
```

I just wanted to know if there is a preferred way in doing this. I imagine there would be a lot of `ChangeNotifierProvider.value()` in my router instead of placing this inside the build method
