### ISSUE TITLE
Is ListenableProvider needed? 

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/provider#39]
@jiaeri said:

Do you think ListenableProvider is needed? It does add some complexity, where it might be cleaner on the consumer side

A ListenableConsumer can just use an ordinary provider, and look like this:

```dart
class ListenableConsumer extends StatelessWidget {
final Widget Function(BuildContext context, T value, Widget child) builder;

ListenableConsumer({Key key, @required this.builder}) : super(key: key);

@override
Widget build(BuildContext context) {
return Consumer(
builder: (context, value) =>
AnimatedBuilder(animation: value, builder: builder));
}
}
```

**Comment by rrousselGit** [comment]
That's a valid point, but it is incompatible with the `of` pattern.

The Flutter way of doing things is wrapping the app into an InheritedWidget and use it through `MyInherited.of(context)`

`provider` is ultimately just syntax sugar for that. 

The issue is, a static method `of`  is not powerful enough to properly make a widget subscribe to a `Listenable`/`Stream` without having a memory leak.

From there we have two solutions:

- Give up on the `of` pattern, and use only a `Consumer` object
- Listen to the object on the provider


____


I picked the second solution as the `of` pattern is closer to how Flutter recommends doing things.

The `Consumer` pattern is more for libraries like Redux or patterns such as BLoC.

**Comment by filiph** [comment]
FWIW, I agree with Remi that having ListenableProvider is useful. Only marginally so, because most of the time when people want to subscribe to something changing they'll go with ChangeNotifier, imho. But there still will be use cases with Listenable.

Eric is right, though, that _having_ that class could give people the wrong idea. "Oh, I need a Listenable here and I need to use it over there, and hey, here's a ListenableProvider widget, so obviously that's what I need to use." Maybe we can be explicit in the documentation? "Please note that you often don't need this class. <insert sample code>".

**Comment by rrousselGit** [comment]
Hum, I think you misunderstood the question Filip.

It's not about `ListenableProvider` vs `ChangeNotifierProvider`
But about `Provider`+`ListenableConsumer` vs `ListenableProvider`+`Consumer`

**Comment by filiph** [comment]
Ah, sorry. 

> But about `Provider`+`ListenableConsumer` vs `ListenableProvider`+`Consumer`

So Eric proposes `ListenableConsumer` to be part of the package? I thought he was just showing example of user code. I'm easily confused, though.

cc actual @jiaeric, I think there was a typo earlier.

**Comment by rrousselGit** [comment]
Indeed.

We can add a `ListenableConsumer` easily.
But then we support two different ways of doing the same thing.
It'll be confusing for users.

**Comment by jiaeric** [comment]
Agreed w/ Remi about not having both. Definitely would prefer having  either ListenableProvider or ListenableConsumer.

To me, providing/getting something is different than listening to changes of that object.
A Consumer from a Provider is guaranteed to have the same reference as the Provider, but not guaranteed to rebuild on changes to values within that reference. Thought of that way, .of() doesn't break with Provider; because someone could just create an AnimatedWidget(animation:Provide.of<foo>...). Listening to changes within the object is almost a separate concern. Although I could see the argument that the two should be the same - do you think people would be confused by the difference?

I see a ListenableConsumer as a convenience class rather than additional concept (Just a Consumer+AnimatedBuilder), but I feel a ListenableProvider feels more like an additional concept, if that makes sense?

**Comment by rrousselGit** [comment]
> Thought of that way, .of() doesn't break with Provider; because someone could just create an AnimatedWidget(animation:Provide.of...)


That's not the same thing. 

Accessing the value is not limited to the build method. Other lifecycles of the widget such as `initState` or `didChangeDependencies` may want to.

But with only a `ListenableConsumer` that is impossible without either reimplementing the listening on every widgets or a library such as `flutter_hooks`.

**Comment by jiaeric** [comment]
But do those other lifecycles need to be aware of Listenable? For initState/didChangeDependencies, that doesn't seem to be the case.

To bring back the original point, 
- Give up on the of pattern, and use only a Consumer object
- Listen to the object on the provider

I think it's more explicit and a cleaner story to only use a Consumer in order to subscribe to Listenable changes. I don't think that static .of functions should be able to subscribe to listenables or streams.

**Comment by rrousselGit** [comment]
> But do those other lifecycles need to be aware of Listenable? 

`didChangeDependencies` definitely need to. That lifecycle exists specifically for this use case — reacting to changes from a provided object.


With the current implementation we can do:

```dart
T previous;

@override
void didChangeDependencies(MyWidget old) {
  final current = Provider.of<T>(context);
  if (previous != current) {
    previous = current;
  } 
}
```

**Comment by jiaeric** [comment]
Fair point with didChangeDependencies - was thinking of initState.

I’m satisfied with this then :)

**Comment by rrousselGit** [comment]
It seems that we all agreed, so I'll close this.
