### ISSUE TITLE
`Locator` field doesn't work on Web with release mode build

### ISSUE THREAD

**Issue by mono0926** [rrousselGit/provider#406]
I've created the reproduced project: https://github.com/mono0926/provider_locator_bug_report.

1. Execute this:

```
flutter run -d chrome --release
```

2. The error log will be shown on Chrome DevTools Console:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/1255062/78554877-e8fa8f00-7846-11ea-81e8-095d8661fc7d.png">

> Error: Could not find the correct Provider<dynamic> above this minified:c2<minified:qF> Widget

The log is written from this:
https://github.com/mono0926/provider_locator_bug_report/blob/ea3f2f65947979a54cfa5fa502c4932ce6825f03/lib/bar.dart#L6-L16

```dart
class Bar {
  Bar({@required this.read}) {
    try {
      print(read<Foo>());
    } catch (e) {
      print(e);
    }
  }

  final Locator read;
}
```

If modified as below, the problem will be fixed.

```dart
class Bar {
  Bar({@required Locator read}) {
    try {
      print(read<Foo>());
    } catch (e) {
      print(e);
    }
  }
}
```

<img width="785" alt="image" src="https://user-images.githubusercontent.com/1255062/78555115-4f7fad00-7847-11ea-9e9e-607fd2124b13.png">

Original code works well except on the web with release build mode.

## Related issues

- #264

**Comment by rrousselGit** [comment]
This looks like a dart2js issue

I've further trimmed the code to remove all Flutter and provider code:

```dart
typedef Locator = void Function<T>();

class Bar {
  Bar({this.read}) {
    read<int>();
  }

  final Locator read;
}

void main() {
  Bar(read: <T>() {
    print(T);
    return null;
  });
}
```


From this snippet, this will print `dynamic` in the console when it should instead print `int`, when using `flutter run -t chrome --release`.

The bug is not on provider's side, so I can't do anything. But I'll make an issue on dart/sdk

**Comment by rrousselGit** [comment]
This looks like a dart2js issue

I've further trimmed the code to remove all Flutter and provider code:

```dart
typedef Locator = void Function<T>();

class Bar {
  Bar({this.read}) {
    read<int>();
  }

  final Locator read;
}

void main() {
  Bar(read: <T>() {
    print(T);
    return null;
  });
}
```


From this snippet, this will print `dynamic` in the console when it should instead print `int`, when using `flutter run -t chrome --release`.

The bug is not on provider's side, so I can't do anything. But I'll make an issue on dart/sdk
