### ISSUE TITLE
dispose keyword provided in Provider but not in ChangeNotifierProvider

### ISSUE THREAD

**Issue by srbcheema1** [rrousselGit/provider#431]
[Documentation](https://pub.dev/documentation/provider/latest/provider/ChangeNotifierProvider-class.html) says that 

> Creates a ChangeNotifier using create and automatically dispose it when ChangeNotifierProvider is removed from the widget tree

While in [Provider](https://pub.dev/documentation/provider/latest/provider/Provider/Provider.html) we need to provide an argument `dispose`.

My question is why is it not in simple Provider, why kept inconsistency in two different providers, if providing dispose argument in one, why not in other.

PS: I could see dispose in listenableProvider also but not in StreamProvider. stream provider docs don't even tell about how dispose works there, it it automatic ? need bit more detail in [SreamProvider docs](https://pub.dev/documentation/provider/latest/provider/StreamProvider-class.html)

**Comment by rrousselGit** [comment]
With `Provider`, it is impossible to dispose the object "automatically", since the library doesn't know how the object exposed works.


With `ChangeNotifierProvider`, a `ChangeNotifier` has a very well defined `dispose` object, so it uses that instead.

With Streams, it cancels the `StreamSubscription`
