### ISSUE TITLE
Allow context.select in didChangeDependencies

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [rrousselGit/provider#475]
## Problem

In some cases, I want to update a value in a `State` both inside of the state itself and *also* when dependencies change.  
This makes it attractive to use `context.select` inside of `didChangeDependencies` as only a particular value of a notifier interested in.

## Solution

I would like to be able to use `context.select` inside of `didChangeDependencies`.

```dart
@override
void didChangeDependencies() {
  super.didChangeDependencies();

  _value = context.select((ValueHolder holder) => holder.value);
}
```

## Workaround

```dart
@override
void didChangeDependencies() {
  super.didChangeDependencies();

  _value = Provider.of<ValueHolder>(context).value;
}
```

**Comment by rrousselGit** [comment]
That is not feasible. select works only in build and cannot work inside didChangeDependencies

**Comment by creativecreatorormaybenot** [comment]
@rrousselGit Can you elaborate?

Also, if you think that it is not feasible as of now, should it not stay open anyway as it would be a nice feature for the future?

**Comment by rrousselGit** [comment]
`select` works by tracking all the calls to `select` by a given widget in a frame.

Since `didChangeDependencies` can be called without `build` being called, that means we'd need to separate the "calls to select withing a frame" into in two categories: didChangeDependences & build

This is not possible to know if `select` was called from `build` or `didChandeDependencies`, making this request infeasible.
If _could_ be possible by changing the framework to expose in release whether a `context` is in `State.didChangeDependencies` or `build`, but the chances of this getting accepted are basically null.
It was already very difficult to obtain a flag to know in **debug** time if a widget is inside `build`.

**Comment by creativecreatorormaybenot** [comment]
And you do not think an extra method is sensible?

**Comment by rrousselGit** [comment]
That would cause a lot of confusion, and slightly decrease the overall performances for an edge-case.

Instead, you can set up a `ProxyProvider` that selects what you need, and consume that `ProxyProvider`.
