### ISSUE TITLE
Difference from Singleton

### ISSUE THREAD

**Issue by taliptako** [rrousselGit/provider#50]
I wonder if Inherited widget is more performant then using Singleton

**Comment by rrousselGit** [comment]
More performant than Singleton, no. But they are pretty fast, (O(1) + a constant factor) so the difference is almost non-existent.

But besides performance, there are a couple of strong points that Singletons do not have.

They:
- act as an abstraction.
- are scoped and overridable
- force structured object graph due to the tree nature and unidirectional data-flow of widgets.
- ensure that dependents are always up to date
