### ISSUE TITLE
.

### ISSUE THREAD

**Issue by TMaxedCode** [rrousselGit/provider#501]
.

**Comment by davidmartos96** [comment]
2 things stand out to me:

1. You are passing down the home page context down your Widget tree. That is not needed. If you use Provider.of(context) with the child widget context, provider will look for it in the widgets above.

2. In the ImageList widget you are getting your model passing the listen flag to false. Since you are in the build method and not in a callback like (onPressed, onReorder...), you should pass that flag as true, which is the default. I believe at the moment you are getting an assertion error. Is that so?
The listen as false would make sense if you were to call Provider.of inside your onReorder function.

**Comment by rrousselGit** [comment]
Hi!

I don't mind helping, but you are giving code without explaining your problem. 
I will need you to tell me what is your issue, or I won't be able to help.

**Comment by TMaxedCode** [comment]
Thank you so much for helping me @davidmartos96 and @rrousselGit. I am trying to find the best way to use Provider in my scenario. I have updated the question above with my error code. Here is the overview of app: I have a home page with a Floating Action Button that lets users select multiple images. Once the images get selected, it updates the value of the Model's images. After that, it will navigate to a StatefulWidget which contains a Reorderable ListView displaying the images.

**Comment by rrousselGit** [comment]
The error talks about a `Consumer<Model>`, but you gave us neither the consumer nor the provider for `Model` – instead we have `ItemModel`

Could you share the code about `Consumer<Model>` and its provider?

**Comment by TMaxedCode** [comment]
Thanks for the reply @rrousselGit . That is a mistake on my part. The error should show ItemModel instead of Model. Sorry about that.

**Comment by rrousselGit** [comment]
As a rough guess, I would say you place the ChangeNotifier<ItemModel> inside the home page.

Place it above MaterialApp instead.

**Comment by TMaxedCode** [comment]
@rrousselGit Thanks for the suggestion. I placed it above my home page and the provider is now easily accessible. Unfortunately, I still got an error. I updated my question above as well as added the error. Thanks again for helping me.
