### ISSUE TITLE
Example for providers

### ISSUE THREAD

**Issue by ManojMM026** [rrousselGit/provider#65]
It will be great if we can have an example of every available provider to start with. Its easier for a guy like me who is just starting with flutter and provider to understand it better.

**Comment by mohammadanton** [comment]
Anyone have Listenable provider example?

**Comment by rrousselGit** [comment]
This is clearly needed. 
But what would be reasonable examples?

Is a counter app using each provider acceptable?

**Comment by rubensdemelo** [comment]
Would like to suggest more real case situations, e.g. http requests

**Comment by ahmetkocadogan** [comment]
As a newbie, it is always hard to figure out how to make authentication with api token and manage auth state within application. This kind of example can be really helpful.

**Comment by HaithamSheshtawy** [comment]
For me, I'm creating my design system. I'm trying to make my atoms listen to the app theme. I need to have a central place.
My current implementation is as following:
`@override
  Widget build(BuildContext context) {
    return Consumer<ThemeDataManager>(
        builder: (context, ThemeDataManager _themeDataManager, _) {
      return Text(
        TextAtomUtils.getTextData(
            data, variationFiltered.textCase ?? DEFAULT_TEXT_CASE),
        locale: locale,
        maxLines: maxLines,
        overflow: overflow,
        semanticsLabel: semanticsLabel,
        softWrap: softWrap,
        strutStyle: strutStyle,
        style: style ?? TextAtomUtils.getStyle(variationFiltered),
        textAlign: textAlign ?? TextAtomUtils.getTextAlign(variationFiltered),
        textDirection: textDirection,
        textScaleFactor: textScaleFactor,
      );
    });`
This approcah is working fine.
instead of the above approach, I need to refactor it to be as follows:

`@override
  Widget build(BuildContext context) {
      return  WithTheme(child: constructChild(),);
  }

 Widget constructChild(){
    return Text(
        TextAtomUtils.getTextData(
            data, variationFiltered.textCase ?? DEFAULT_TEXT_CASE),
        locale: locale,
        maxLines: maxLines,
        overflow: overflow,
        semanticsLabel: semanticsLabel,
        softWrap: softWrap,
        strutStyle: strutStyle,
        style: style ?? TextAtomUtils.getStyle(variationFiltered),
        textAlign: textAlign ?? TextAtomUtils.getTextAlign(variationFiltered),
        textDirection: textDirection,
        textScaleFactor: textScaleFactor,
      );
  }`

but unfortunately, it is not working.

**Comment by HaithamSheshtawy** [comment]
Finally, I succeeded to fix it as follows:
```dart
class WithTheme<T extends ThemeDataManager> extends StatelessWidget {
   WithTheme({@required this.builder});

  Widget Function(BuildContext context, T model, Widget child) builder;

  @override
  Widget build(BuildContext context) {
    return Consumer<T>(builder: builder,);
  }
```

**Comment by HaithamSheshtawy** [comment]
I recommended this Structure for Provider.
https://medium.com/flutter-community/flutter-architecture-provider-implementation-guide-d33133a9a4e8

**Comment by bradyt** [comment]
@rrousselGit I think adding super simple cases of each approach is a great idea. I don't see any reason to omit the simple cases. In addition to any less trivial cases people feel should be covered.

**Comment by bradyt** [comment]
There are now two examples linked at https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple#putting-it-all-together. [Provider counter](https://github.com/flutter/samples/tree/master/provider_counter) and [provider shopper](https://github.com/filiph/samples/tree/provider-shopper).

**Comment by chimon2000** [comment]
What stuck out to me after watching [provider episode](https://youtu.be/HrBiNHEqSYU) on The Boring Show, was that just simple documentation on how to use each provider, their tradeoffs, and example use cases would go a long way.  

In this case, the showrunners fell back to ChangeNotifierProvider because it was not immediately obvious how to use ValueListenableProvider in the current documentation.

**Comment by rrousselGit** [comment]
Hum, to be honest, guessing others' problem is not part of my skills.

It'd help me tremendously if peoples could:
- ask clear questions about what they don't understand
- make detailed specs for their example needs


____

>  it was not immediately obvious how to use ValueListenableProvider in the current documentation.

Nowadays it's not very useful.
It was a first attempt at fusing multiple providers into one & pushing immutable values, by having a `ValueNotifier` subclass listen to other `ChangeNotifier` internally and rebuild `value` when needed.

But `ProxyProvider` is much better at that job. Maybe I should just mark it as `@Deprecated`.

**Comment by rrousselGit** [comment]
Also, bear in mind that there's not one finite architecture using `provider`. 

Some do `scoped_model`, others do `Mobx`, or others go for `setState`.

A complex example would implicitly mean that one of them is better than the others when that's not necessarily true,

**Comment by zrfrank** [comment]
I really wish to have some DOs and DONTs in the documentation.

**Comment by bradyt** [comment]
Perhaps if we there were a set of examples at the most introductory level, to give a notion of each provider. Similar to the examples at https://medium.com/flutter/managing-flutter-application-state-with-inheritedwidgets-1140452befe1.

@HansMuller, can we convince you to write a followup along the lines of this provider library?

**Comment by bastienJS** [comment]
> This is clearly needed.
> But what would be reasonable examples?
> 
> Is a counter app using each provider acceptable?

A counter app is counterproductive...

The api says me nothing. Its cryptic. How to create parent : child relations with n-levels ?

where each level has behavior like canAdd,canDelete, is whole parent/children form valid.

I rather use no statement and hack the code native instead of asking 1000 questions for every easy sample I can not find.

How to nest models correctly that I do not get Stack overflow exceptions? I got many of them!

If there is no easy access devs will dump that library!

**Comment by rrousselGit** [comment]
I'll close this as I do not have the time to make complete app samples.
Also, there are many examples available on medium, youtube, udemy...

I know this is not what you would like to hear, but that's just not my thing and I'm working on my free time.

But I would encourage people to make pull requests to add their articles to the README or add examples.

**Comment by jonataswalker** [comment]
Not a finished (nor will be) app but hopefully can help as a start.

https://github.com/jonataswalker/flutter-example
